export const DUMMYTASKS = [
  {
    id: 1,
    userId: 1,
    title: 'Revisar planejamento semanal',
    summary: 'Organizar prioridades e revisar metas da semana.',
    dueDate: '2026-06-01',
  },
  {
    id: 2,
    userId: 2,
    title: 'Atualizar documentação do projeto',
    summary: 'Adicionar informações recentes sobre os componentes.',
    dueDate: '2026-06-02',
  },
  {
    id: 3,
    userId: 3,
    title: 'Corrigir bug no formulário',
    summary: 'Investigar erro de validação nos campos obrigatórios.',
    dueDate: '2026-06-03',
  },
  {
    id: 4,
    userId: 4,
    title: 'Preparar apresentação',
    summary: 'Criar slides para reunião com a equipe.',
    dueDate: '2026-06-04',
  },
  {
    id: 5,
    userId: 5,
    title: 'Revisar pull requests',
    summary: 'Analisar alterações pendentes no repositório.',
    dueDate: '2026-06-05',
  },
  {
    id: 6,
    userId: 6,
    title: 'Configurar ambiente de testes',
    summary: 'Garantir que o ambiente esteja pronto para execução dos testes.',
    dueDate: '2026-06-06',
  },
  {
    id: 7,
    userId: 1,
    title: 'Criar componente de tarefas',
    summary: 'Implementar estrutura inicial para exibição das tarefas.',
    dueDate: '2026-06-07',
  },
  {
    id: 8,
    userId: 2,
    title: 'Refatorar serviços',
    summary: 'Melhorar organização dos serviços da aplicação.',
    dueDate: '2026-06-08',
  },
  {
    id: 9,
    userId: 3,
    title: 'Adicionar testes unitários',
    summary: 'Criar testes para componentes principais.',
    dueDate: '2026-06-09',
  },
  {
    id: 10,
    userId: 4,
    title: 'Validar responsividade',
    summary: 'Testar layout em telas pequenas e médias.',
    dueDate: '2026-06-10',
  },
  {
    id: 11,
    userId: 5,
    title: 'Ajustar estilos globais',
    summary: 'Padronizar cores, fontes e espaçamentos.',
    dueDate: '2026-06-11',
  },
  {
    id: 12,
    userId: 6,
    title: 'Criar tela de detalhes',
    summary: 'Exibir informações completas de uma tarefa selecionada.',
    dueDate: '2026-06-12',
  },
  {
    id: 13,
    userId: 1,
    title: 'Implementar filtro por usuário',
    summary: 'Mostrar apenas tarefas relacionadas ao usuário selecionado.',
    dueDate: '2026-06-13',
  },
  {
    id: 14,
    userId: 2,
    title: 'Organizar backlog',
    summary: 'Classificar tarefas futuras por prioridade.',
    dueDate: '2026-06-14',
  },
  {
    id: 15,
    userId: 3,
    title: 'Revisar nomenclatura dos arquivos',
    summary: 'Garantir consistência nos nomes dos arquivos do projeto.',
    dueDate: '2026-06-15',
  },
  {
    id: 16,
    userId: 4,
    title: 'Melhorar acessibilidade',
    summary: 'Adicionar textos alternativos e melhorar navegação por teclado.',
    dueDate: '2026-06-16',
  },
  {
    id: 17,
    userId: 5,
    title: 'Criar interface de tarefa',
    summary: 'Definir contrato TypeScript para objetos de tarefa.',
    dueDate: '2026-06-17',
  },
  {
    id: 18,
    userId: 6,
    title: 'Implementar estado inicial',
    summary: 'Adicionar tarefas mockadas para desenvolvimento.',
    dueDate: '2026-06-18',
  },
  {
    id: 19,
    userId: 1,
    title: 'Adicionar mensagem vazia',
    summary: 'Exibir aviso quando o usuário não possuir tarefas.',
    dueDate: '2026-06-19',
  },
  {
    id: 20,
    userId: 2,
    title: 'Criar botão de conclusão',
    summary: 'Permitir marcar uma tarefa como concluída.',
    dueDate: '2026-06-20',
  },
  {
    id: 21,
    userId: 3,
    title: 'Revisar imports',
    summary: 'Remover imports não utilizados nos componentes.',
    dueDate: '2026-06-21',
  },
  {
    id: 22,
    userId: 4,
    title: 'Atualizar README',
    summary: 'Adicionar instruções para rodar o projeto localmente.',
    dueDate: '2026-06-22',
  },
  {
    id: 23,
    userId: 5,
    title: 'Melhorar nomes das variáveis',
    summary: 'Deixar o código mais claro e legível.',
    dueDate: '2026-06-23',
  },
  {
    id: 24,
    userId: 6,
    title: 'Criar mock de tarefas',
    summary: 'Separar dados fictícios em um arquivo dedicado.',
    dueDate: '2026-06-24',
  },
  {
    id: 25,
    userId: 1,
    title: 'Adicionar contador de tarefas',
    summary: 'Exibir quantidade de tarefas do usuário selecionado.',
    dueDate: '2026-06-25',
  },
  {
    id: 26,
    userId: 2,
    title: 'Configurar Prettier',
    summary: 'Garantir formatação consistente do código.',
    dueDate: '2026-06-26',
  },
  {
    id: 27,
    userId: 3,
    title: 'Criar layout do card',
    summary: 'Definir estrutura visual para cada tarefa.',
    dueDate: '2026-06-27',
  },
  {
    id: 28,
    userId: 4,
    title: 'Testar fluxo de seleção',
    summary: 'Validar se as tarefas mudam ao selecionar outro usuário.',
    dueDate: '2026-06-28',
  },
  {
    id: 29,
    userId: 5,
    title: 'Adicionar data limite',
    summary: 'Exibir prazo de entrega em cada tarefa.',
    dueDate: '2026-06-29',
  },
  {
    id: 30,
    userId: 6,
    title: 'Criar estilo para tarefa vencida',
    summary: 'Destacar visualmente tarefas com prazo expirado.',
    dueDate: '2026-06-30',
  },
  {
    id: 31,
    userId: 1,
    title: 'Implementar ordenação por data',
    summary: 'Ordenar tarefas pela data de vencimento.',
    dueDate: '2026-07-01',
  },
  {
    id: 32,
    userId: 2,
    title: 'Adicionar campo de prioridade',
    summary: 'Permitir classificar tarefas por baixa, média ou alta prioridade.',
    dueDate: '2026-07-02',
  },
  {
    id: 33,
    userId: 3,
    title: 'Criar modal de nova tarefa',
    summary: 'Exibir formulário para cadastrar uma nova tarefa.',
    dueDate: '2026-07-03',
  },
  {
    id: 34,
    userId: 4,
    title: 'Validar formulário de tarefa',
    summary: 'Impedir cadastro com título ou data vazios.',
    dueDate: '2026-07-04',
  },
  {
    id: 35,
    userId: 5,
    title: 'Adicionar botão de exclusão',
    summary: 'Permitir remover tarefas da lista.',
    dueDate: '2026-07-05',
  },
  {
    id: 36,
    userId: 6,
    title: 'Criar confirmação de remoção',
    summary: 'Solicitar confirmação antes de excluir uma tarefa.',
    dueDate: '2026-07-06',
  },
  {
    id: 37,
    userId: 1,
    title: 'Implementar edição de tarefa',
    summary: 'Permitir alterar título, resumo e data limite.',
    dueDate: '2026-07-07',
  },
  {
    id: 38,
    userId: 2,
    title: 'Separar lógica de tarefas',
    summary: 'Mover regras de manipulação para uma classe ou serviço.',
    dueDate: '2026-07-08',
  },
  {
    id: 39,
    userId: 3,
    title: 'Criar pipe para data',
    summary: 'Formatar datas exibidas na interface.',
    dueDate: '2026-07-09',
  },
  {
    id: 40,
    userId: 4,
    title: 'Melhorar feedback visual',
    summary: 'Adicionar estados visuais para ações do usuário.',
    dueDate: '2026-07-10',
  },
  {
    id: 41,
    userId: 5,
    title: 'Adicionar busca de tarefas',
    summary: 'Permitir encontrar tarefas pelo título.',
    dueDate: '2026-07-11',
  },
  {
    id: 42,
    userId: 6,
    title: 'Criar agrupamento por status',
    summary: 'Separar tarefas pendentes e concluídas.',
    dueDate: '2026-07-12',
  },
  {
    id: 43,
    userId: 1,
    title: 'Revisar performance da lista',
    summary: 'Garantir renderização eficiente com trackBy ou track.',
    dueDate: '2026-07-13',
  },
  {
    id: 44,
    userId: 2,
    title: 'Adicionar armazenamento local',
    summary: 'Salvar tarefas no localStorage temporariamente.',
    dueDate: '2026-07-14',
  },
  {
    id: 45,
    userId: 3,
    title: 'Criar mensagens de erro',
    summary: 'Exibir mensagens amigáveis para falhas de operação.',
    dueDate: '2026-07-15',
  },
  {
    id: 46,
    userId: 4,
    title: 'Revisar estrutura de pastas',
    summary: 'Organizar componentes e dados mockados.',
    dueDate: '2026-07-16',
  },
  {
    id: 47,
    userId: 5,
    title: 'Adicionar status da tarefa',
    summary: 'Indicar se a tarefa está pendente, em andamento ou concluída.',
    dueDate: '2026-07-17',
  },
  {
    id: 48,
    userId: 6,
    title: 'Criar componente de lista',
    summary: 'Separar renderização da lista de tarefas em componente próprio.',
    dueDate: '2026-07-18',
  },
  {
    id: 49,
    userId: 1,
    title: 'Finalizar ajustes visuais',
    summary: 'Revisar espaçamentos e alinhamentos da interface.',
    dueDate: '2026-07-19',
  },
  {
    id: 50,
    userId: 2,
    title: 'Preparar entrega da versão inicial',
    summary: 'Conferir funcionalidades principais antes da entrega.',
    dueDate: '2026-07-20',
  },
];
